### ISSUE TITLE
Default Timezone when no X-WR-TIMEZONE is set in ics file

### ISSUE THREAD

**Issue by Heart1010** [controlz/CalFileParser#2]
I'm confronted with a ics file which don't have any timezone values in it

``` BEGIN:VCALENDAR
VERSION:2.0
PRODID:xy
METHOD:PUBLISH
BEGIN:VEVENT
UID:20140925T175944CEST-0480Sdk86c@xy
DTSTAMP:20140925T155944Z
DESCRIPTION:This is a test
DTSTART:20140727T150000
DTEND:20140727T170000
SUMMARY:This is the summary
END:VEVENT
```

Such ics files can't be processed with your parses because 

```
Warning: DateTime::createFromFormat() expects parameter 3 to be DateTimeZone, null given in /kunden/277447/url/CalFileParser.php on line 258
```

How to handle that?

Can you integrate a "default timezone" paramater which is used in such cases when the ics file has no timezone in it?

**Comment by Jany-M** [comment]
@controlz I second the request, but I think that it should also be a last resort, since the parameter TZID is usually specified in .ics

MS doesnt use default timezones (yay), so the script probably needs to check against [this table](http://www.unicode.org/cldr/charts/latest/supplemental/zone_tzid.html) for conversion, defaulting to first match in case of various options for same MS timezone definition.

eg.
`Romance Standard Time	001	Europe/Paris
Romance Standard Time	BE	Europe/Brussels
Romance Standard Time	DK	Europe/Copenhagen
Romance Standard Time	ES	Europe/Madrid Africa/Ceuta
Romance Standard Time	FR	Europe/Paris`
which are essentially the exact timezone.

**Comment by cscheltinga** [comment]
Still an issue, and I can't get to solve it. It's indeed a MS .ics file... Any ideas?

**Comment by panfanky** [comment]
The problem remains when the timezone string is not understood, would be better to get data based on default timezone, then
`Fatal error: Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone (Europe/Bratislava;VALUE=DATE) `
